// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SBMProject

#ifndef _SBMPROJECT_UI_H
#define _SBMPROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_pngwing_com_png);    // assets/pngwing.com.png
LV_IMG_DECLARE(ui_img_1871343664);    // assets/pngwing.com (1).png






void ui_init(void);
void ui_init2();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
